### ISSUE TITLE
update templates to reflect change in OVC client

### ISSUE THREAD

**Issue by alichaddad** [openvcloud/ays_templates#1]
Update the templates to be in line to changes introduced in https://github.com/Jumpscale/lib9/blob/9.3.0/JumpScale9Lib/clients/openvcloud/OpenvCloudClientFactory.py(version:9.3.0).

Stacktrace from install action of a `vdc` service:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vdc/ef39f226228fa1b68114d6fd5d195293.py", line 14, in install
    cl = j.clients.openvcloud.getFromService(g8client)
AttributeError: 'OpenvCloudClientFactory' object has no attribute 'getFromService'
```

**Comment by yveskerwyn** [comment]
Let’s make sure that we also have a 9.2.0/Pre-9.3.0 compatible branch
