### ISSUE TITLE
SSH session not active errors

### ISSUE THREAD

**Issue by yveskerwyn** [openvcloud/ays_templates#11]
Using 9.2.1

We start with following blueprints:

```yaml
g8client__cl:
  url: 'be-gen-1.demo.greenitglobe.com'
  login: '***'
  password: '***'
  account: 'GnRhmdyp6aPIl0fyLe5W'
actions:
  - action: install
    actor: g8client
    service: cl

vdc__vdc2delete:
  g8client: 'cl'
  location: 'be-gen-1'
  maxMemoryCapacity: -1
  maxDiskCapacity: -1
  maxCPUCapacity: -1
  maxNumPublicIP: -1

actions:
  - action: install
    actor: vdc
    service: vdc2delete

node.ovc__vm2delete:
  vdc: 'vdc2delete'
  bootdiskSize: 10
  memory: 2
  osImage: Ubuntu 16.04 x64
  description: test
actions:
  - action: install
    actor: node.ovc
    service: vm2delete
```

Then we delete the VM using following blueprint:
```yaml
actions:
  - action: uninstall
    actor: node.ovc
    service: vm2delete
```

In the output we see follow trace back:
```python
Error of job: node.ovc!26MX3bhZ6tXvvySxVfA5 (install):
*TRACEBACK*********************************************************************************
job: node.ovc!26MX3bhZ6tXvvySxVfA5 (install) failed:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.ovc/0496f3155d6c05fc43e7b81ea6095763.py", line 155, in install
    raise e
  File "/tmp/actions/node.ovc/0496f3155d6c05fc43e7b81ea6095763.py", line 126, in install
    space.configure_machine(machine=machine, name=service.name, sshkey_name=sshkey.name, sshkey_path=key_path)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/OpenvCloudClientFactory.py", line 630, in configure_machine
    prefab.core.hostname = name  # make sure hostname is set
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 736, in hostname
    self.file_write(hostfile, val)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 871, in file_write
    path=path, content=content, mode=mode, owner=owner, group=group, append=append)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 501, in file_write
    res = self.execute(cmd, hide=True)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorSSH.py", line 143, in execute
    cmds2, die=die, showout=showout)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/ssh/SSHClient.py", line 232, in execute
    ch = self.transport.open_session()
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 767, in open_session
    timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 854, in open_channel
    raise SSHException('SSH session not active')
paramiko.ssh_exception.SSHException: SSH session not active

******************************************************************************************
```

While this is not problematic at this, it is when trying to create a new VM using the same repo:
```yaml
node.ovc__newvm:
  vdc: 'vdc2delete'
  bootdiskSize: 10
  memory: 2
  osImage: Ubuntu 16.04 x64
  description: test
actions:
  - action: install
    actor: node.ovc
    service: newvm
~
```

Machine get created succesfully, but with errors in output (failing run).

Traceback:
```python
Error of job: node.ovc!newvm (install):
*TRACEBACK*********************************************************************************
job: node.ovc!newvm (install) failed:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.ovc/9dd4be6031078007ff05b67aae3771a6.py", line 155, in install
    raise e
  File "/tmp/actions/node.ovc/9dd4be6031078007ff05b67aae3771a6.py", line 126, in install
    space.configure_machine(machine=machine, name=service.name, sshkey_name=sshkey.name, sshkey_path=key_path)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/OpenvCloudClientFactory.py", line 630, in configure_machine
    prefab.core.hostname = name  # make sure hostname is set
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 736, in hostname
    self.file_write(hostfile, val)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 871, in file_write
    path=path, content=content, mode=mode, owner=owner, group=group, append=append)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 501, in file_write
    res = self.execute(cmd, hide=True)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorSSH.py", line 143, in execute
    cmds2, die=die, showout=showout)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/ssh/SSHClient.py", line 232, in execute
    ch = self.transport.open_session()
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 767, in open_session
    timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 854, in open_channel
    raise SSHException('SSH session not active')
paramiko.ssh_exception.SSHException: SSH session not active


******************************************************************************************
```

**Comment by yveskerwyn** [comment]
solved: https://github.com/Jumpscale/lib9/commit/9a27c6a9e200fd6d8a5ef39040d6f57f0e4eb646
