### ISSUE TITLE
Unable to uninstall an OVC account

### ISSUE THREAD

**Issue by yveskerwyn** [openvcloud/ays_templates#12]
First we execute a run based on following blueprint:
```yaml
g8client__cl:
  url: 'be-gen-1.demo.greenitglobe.com'
  login: '****'
  password: '****'
  account: 'nXyBBnpJbGIxllZ6IaOS'

vdc__vdc2delete:
  g8client: 'cl'
  location: 'be-gen-1'

node.ovc__vm2delete:
  vdc: 'vdc2delete'
  bootdiskSize: 10
  memory: 2
  osImage: 'Ubuntu 16.04 x64'
  description: 'test'

actions:
  - action: install
```

Then we execute a new run based on following blueprint:
```yaml
actions:
  - action: 'uninstall'
```

This results in:
```bash
RUN:2f0346e348df431afb803a7ac972df53 (error)
step:1 (ok)
- os.ssh.ubuntu             vm2delete                      | stop            (ok)
- sshkey                    auto_0                         | stop            (ok)
- account                   nXyBBnpJbGIxllZ6IaOS           | uninstall       (ok)
- g8client                  cl                             | stop            (ok)
step:2 (ok)
- g8client                  cl                             | uninstall       (ok)
- os.ssh.ubuntu             vm2delete                      | uninstall       (ok)
- sshkey                    auto_0                         | uninstall       (ok)
step:3 (error)
- node.ovc                  vm2delete                      | stop            (error)
step:4 (new)
- node.ovc                  vm2delete                      | uninstall       (new)
- vdc                       vdc2delete                     | stop            (new)
step:5 (new)
- vdcfarm                   auto_20                        | stop            (new)
- vdc                       vdc2delete                     | uninstall       (new)
step:6 (new)
- vdcfarm                   auto_20                        | uninstall       (new)
```

Traceback:
```python
[Mon15 17:39] - RunStep.py          :84  :j.atyourservice.server         - ERROR    - job: node.ovc!vm2delete (stop) failed:
'vm2delete'
[Mon15 17:39] - RunStep.py          :87  :j.atyourservice.server         - INFO     - runstep 3: error
[Mon15 17:39] - Run.py              :162 :j.atyourservice.server         - ERROR    - error during execution of step 3 in run 2f0346e348df431afb803a7ac972df53
Error of job: node.ovc!vm2delete (stop):
*TRACEBACK*********************************************************************************
job: node.ovc!vm2delete (stop) failed:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.ovc/6b4833e312ed4fe779724da80ffa5660.py", line 203, in stop
    machine = space.machines[job.service.name]
KeyError: 'vm2delete'


******************************************************************************************
```

**Comment by yveskerwyn** [comment]
Closing because specifying the account service explicitly is a more than acceptable solution:

```yaml
actions:
  - action: 'uninstall'
     actor: 'account'
     service: 'account-for-testing-issue4'
```
